### PR TITLE
Add explicit else blocks to style guide

### PR DESCRIPTION
**Pull request by carver**
This is something that @pipermerriam and I have talked about a few times, and he convinced me that it's appealing to quickly/visually see the shape of the control flow. I think we are mildly consistent about following the pattern already. I've certainly given that feedback to external contributors as well.

I like it, but I don't feel super strongly about it. More important is for us to agree as a team, because the worst option is to use *both* conventions.

cc @ethereum/snake-charmers
_^ testing this out. Does it ping everyone on the team?_

### CODE REVIEW

**Comment by davesque** [comment]
Honestly, I often find that way less readable.  For example,
```python
def foo():
    if guard_condition:
        return False
    else:
        if guard_condition2:
            return False
        else:
            if guard_condition3:
                return False
            else:
                return True
```
as opposed to this...
```python
def foo():
    if guard_condition:
        return False

    if guard_condition2:
        return False

    if guard_condition3:
        return False

    return True
```
I feel like using guards to make code more flat is a really common pattern that I use a lot to make things more readable.  Would be kinda sad to have let go of that.

**Comment by davesque** [comment]
I suppose maybe what you're proposing has more to do with when you have a simple if/else at the end of a function.  If that's the case, I don't have as much of an issue with it.  I dunno.  Even that situation already seems pretty simple so I wonder if it's really all that much less readable to not have the explicit else.

**Comment by lithp** [comment]
I've found an example of this style being followed in py-trie:

https://github.com/ethereum/py-trie/blob/f33a05a40ff2aa5ad0c28e7793496c10b18b7753/trie/utils/nodes.py#L37-L50

And here's an example of it not being followed:

https://github.com/ethereum/py-trie/blob/f33a05a40ff2aa5ad0c28e7793496c10b18b7753/trie/utils/nodes.py#L120-L142

The outer if-elif-else block uses an else to wrap up, and while I slightly prefer the explicit else I think either style would be equally readable there. The inner if blocks, however, do not follow this style. I slightly prefer keeping this style canonical. I think the reason why I prefer it is that this style results in less indentation and room for longer comments. Both are around equally readable though.

**Comment by davesque** [comment]
Actually, I have to admit that maybe I was getting a bit carried away earlier.  Now I'm looking at the example I gave and it seems really contrived.  I suppose you could just as easily do this...
```python
def foo():
    if condition1:
        return False
    elif condition2:
        return False
    elif condition3:
        return False
    else:
        return True
```
...and the code would be basically as flat.

**Comment by cburgdorf** [comment]
I'm personally not a fan of the explicit else. It boils down to the fact that I often think brevity actually results in more readable code. Obviously not to the extend where things are given oddly short names or obscure magical tricks are being used but in general I lean on the side that thinks the less code I have to parse the better.

Just take the simple example of lazy properties. The `else` plus the fact that I now have two `return` statements just feels like a unnecessary distraction to me. Given a few of these cases in a single file it adds up and results in a larger file to navigate through.

Without else:
```python
    @property
    def some_thing(self) -> SomeThing:
        if self._some_thing is None:
            self._some_thing = SomeThing()

        return self._some_thing
```

With else:
```python
    @property
    def some_thing(self) -> SomeThing:
        if self._some_thing is None:
            self._some_thing = SomeThing()
            return self._some_thing
        else
            return self._some_thing
```

Or maybe my example just takes the proposed rule to the extreme and this rule change doesn't actually advocate for the second example? :thinking:

**Comment by davesque** [comment]
@cburgdorf That's basically where I stand. I prefer brevity as long as it's not like wizardry. And leaving out the "else" doesn't seem like wizardry :).

**Comment by carver** [comment]
> Or maybe my example just takes the proposed rule to the extreme and this rule change doesn't actually advocate for the second example?

Yeah, maybe I can reword to make it clear that this isn't the case I was thinking of. When you have an `if` block followed by something that happens *whether or not the conditional is true* then I agree it's shorter (and clearer!) to not duplicate the code in both blocks.

I'm specifically talking about cases where the if block *short-circuits* via `return` or `raise` and so the code that follows is only running in the non-conditional case (implicitly). To me, it's nice to have this visual when reviewing code:

```py
def dothings():
  ... some code ...

  if conditional:
    ... some code I haven't read ...

  ... this code runs regardless of conditional ...
```


> I've found an example of this style being followed in py-trie:
> 
> https://github.com/ethereum/py-trie/blob/f33a05a40ff2aa5ad0c28e7793496c10b18b7753/trie/utils/nodes.py#L37-L50
> 
> ```python
> def get_node_type(node):
>     if node == BLANK_NODE:
>         return NODE_TYPE_BLANK
>     elif len(node) == 2:
>         key, _ = node
>         nibbles = decode_nibbles(key)
>         if is_nibbles_terminated(nibbles):
>             return NODE_TYPE_LEAF
>         else:
>             return NODE_TYPE_EXTENSION
>     elif len(node) == 17:
>         return NODE_TYPE_BRANCH
>     else:
>         raise InvalidNode("Unable to determine node type")
> ```

Yeah, this is a great example. Does anyone prefer this alternative?

```py
def get_node_type(node):
    if node == BLANK_NODE:
        return NODE_TYPE_BLANK
    elif len(node) == 2:
        key, _ = node
        nibbles = decode_nibbles(key)
        if is_nibbles_terminated(nibbles):
            return NODE_TYPE_LEAF

        return NODE_TYPE_EXTENSION
    elif len(node) == 17:
        return NODE_TYPE_BRANCH
    else:
        raise InvalidNode("Unable to determine node type")
```

(I don't)

---

> https://github.com/ethereum/py-trie/blob/f33a05a40ff2aa5ad0c28e7793496c10b18b7753/trie/utils/nodes.py#L120-L142
> The inner if blocks, however, do not follow this style. I prefer keeping the way it is now canonical. I think the reason is that this style results in less indentation and room for longer comments. Both are around equally readable though.

In this example, I think neither format is good. If we allow implicit else blocks, though, then it's easier to let it slide in a review. If we prefer not to use implicit else blocks, then it forces us to come up with a third alternative, which seems better:

```py
def parse_branch_node(serialized_node):
    # note that this falls into the "guard at the beginning of a function" exception,
    # if you prefer not to use an else block
    if len(node) != 65:
        raise InvalidNode("Invalid branch node, both child node should be 32 bytes long each")

    # Output: node type, left child, right child
    return BRANCH_TYPE, serialized_node[1:33], serialized_node[33:]

def parse_node(node):
    """
    Input: a serialized node
    """
    if node is None or node == b'':
        raise InvalidNode("Blank node is not a valid node type in Binary Trie")
    elif node[0] == BRANCH_TYPE:
        return parse_branch_node(node)
    elif node[0] == KV_TYPE:
        return parse_kv_node(node)
    elif node[0] == LEAF_TYPE:
        return parse_leaf_node(node)
    else:
        raise InvalidNode("Unable to parse node")
```

---

No matter the style we decide on, these are *should* directives, not *must* directives, so there's definitely room to make special cases. It shouldn't hold up a PR (it would be more like a style comment on an accepted PR).

**Comment by carver** [comment]
There was enough contention on this point that I'll close it until we can come up with something that's broadly satisfactory

**Pull request closed without merging**
